### ISSUE TITLE
Installation fail with node v11.11.0, npm 6.9.0, macOS 10.14.3

### ISSUE THREAD

**Issue by bouvin** [Webstrates/file-system#14] opened 2019-03-18 11:05 UTC
I ran into the following trying to install wfs on a fresh node install
I attempted the installation with and without sudo.
[wfs-install-fail.txt](https://github.com/Webstrates/file-system/files/2977702/wfs-install-fail.txt)

[2019-03-18T10_58_03_960Z-debug.log](https://github.com/Webstrates/file-system/files/2977730/2019-03-18T10_58_03_960Z-debug.log)
[2019-03-18T10_58_42_196Z-debug.log](https://github.com/Webstrates/file-system/files/2977731/2019-03-18T10_58_42_196Z-debug.log)

**Comment by kbadk** [comment] 2019-03-18 11:53
Hi, I think this is due to homebrew messing up permissions on 10.14. I wasn't able to reproduce on 10.13, but I could on 10.14.

The easiest fix seems to be [installing with `--allow-root`](https://github.com/nodejs/node-gyp/issues/454) until homebrew gets sorted out. 

    sudo npm install -g webstrates-file-system --allow-root

There is no install script or anything of the like in Webstrates file system, so unfortunately, we don't have much control over the process and thus no way to fix it other than workarounds like this.

Please let me know if this worked for you.

**Comment by bouvin** [comment] 2019-03-18 12:32
I am indeed using brew. Regrettably, this is what I got:
[wfs-install-fail.txt](https://github.com/Webstrates/file-system/files/2978033/wfs-install-fail.txt)

**Comment by kbadk** [comment] 2019-03-18 13:35
That's disappointing, both `--unsafe-perm` and `--allow-root` worked for me on 10.14, but this was also with `npm` installed using `n`, the node version manager, as [recommended by npm to resolve EACCESS permissions errors](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally).

You could try simply:

    sudo npm install -g webstrates-file-system --unsafe-perm

If that doesn't help, I'd follow npm's recommendation and use `n`:

    sudo npm install -g n
    sudo n latest

Close and reopen terminal, then:

    sudo npm install -g webstrates-file-system

(Potentially combined with either `--allow-root` or `--unsafe-perm`.)

Hopefully, `npm` will let you install `n`.

Otherwise, the last-ditch effort will have to be installing wfs manually and creating an alias, by navigating to an appropriate folder, installing wfs there

    sudo npm install webstrates-file-system

and then creating an alias in your bash/zsh config file:

    alias wfs='/path/to/Webstrates-file-system/index.js'

(Remember to reopen your terminal afterwards, to reload the config file).

Meanwhile, I'll try to setup a new 10.14 VM and replicate your setup. But using `n` _should_ work...

**Comment by bouvin** [comment] 2019-03-18 13:51
Hi

The former did the trick.  Thank you for your prompt help.

Cheers
	Niels Olof



> On 18 Mar 2019, at 14.35, Kristian Antonsen <notifications@github.com> wrote:
> 
> That's disappointing, both --unsafe-perm and --allow-root worked for me, but this was also with npm installed using n, the node version manager, as recommended by npm to resolve EACCESS permissions errors.
> 
> You could try simply:
> 
> sudo npm install -g webstrates-file-system --unsafe-perm
> 
> If that doesn't help, I'd follow npm's recommendation and use n:
> 
> sudo npm install -g n
> sudo n latest
> sudo npm install -g webstrates-file-system
> 
> Hopefully, npm will let you install n.
> 
> Otherwise, the last-ditch effort will have to be installing wfs manually and creating an alias, by navigating to an appropriate folder, installing wfs there
> 
> sudo npm install webstrates-file-system
> 
> and then creating an alias in your bash/zsh config file:
> 
> alias wfs='/path/to/Webstrates-file-system/index.js'
> 
> (Remember to reopen your terminal afterwards, to reload the config file).
> 
> Meanwhile, I'll try to setup a new 10.14 VM and replicate your setup. But using n should work...
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Niels Olof Bouvin, Ph.D.  http://www.bouvin.net/ Voice: +45 87 15 61 76 \ /
In omnibus requiem quaesivi, et nusquam inveni nisi in angulo cum libro (")
Associate Professor @ Department of Computer Science, Aarhus Univ., Denmark

**Comment by kbadk** [comment] 2019-03-18 13:58
Great! You're welcome.

**Closed as completed by kbadk** 2019-03-18 13:58 UTC
